export {default as checkForEmotion} from './checkForEmotion'
export {default as checkForDefinition} from './checkForDefinition'
export {default as checkForMath} from './checkForMath'
export {default as checkForWeather} from './checkForWeather'
export {default as calculate} from './calculate'
