export {default as NewAudioRecognition} from './newAudioRecognition'
export {default as Home} from './home'
export {default as Choose} from './choose'
export {default as Instructions} from './instructions'
export {default as About} from './about'
export {default as Navbar} from './navbar'
